config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  link_on_import: absolute
  link_dotfile_default: absolute
dotfiles:
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
    link: absolute
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    link: absolute
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    link: absolute
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    link: absolute
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
    link: absolute
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: absolute
  d_omf:
    src: config/omf
    dst: ~/.config/omf
    link: absolute
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
    link: absolute
  d_bin:
    src: bin
    dst: ~/bin
profiles:
  tbarch:
    dotfiles:
    - d_polybar
    - d_fish
    - d_nvim
    - f_gitconfig
    - d_alacritty
    - d_i3
    - d_omf
    - f_tmux.conf
  LD94V3GWK7:
    dotfiles:
    - d_fish
    - d_nvim
    - f_gitconfig
    - d_alacritty
    - d_omf
    - f_tmux.conf
    - d_bin
