config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_fish:
    src: config/fish
    dst: ~/.config/fish
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
profiles:
  tbarch:
    dotfiles:
    - d_polybar
    - d_fish
    - d_nvim
    - f_gitconfig
  LD94V3GWK7:
    dotfiles:
    - d_polybar
    - d_fish
    - d_nvim
    - f_gitconfig
