[shell]
program = "/opt/homebrew/bin/fish"

[window]
dimensions = { columns = 250, lines = 60 }
startup_mode = "Fullscreen"

[colors.primary]
background = "#1f1f28"

[colors]
cursor = { text = "CellBackground", cursor = "#c7c7c7" }

[font]
normal = { family = "Consolas NF", style = "Book" }
bold = { family = "Consolas NF", style = "Bold" }
italic = { family = "Consolas NF", style = "Italic" }
bold_italic = { family = "Consolas NF", style = "Bold Italic" }
size = 15

[keyboard]
bindings = [
  { key = "Enter", mods = "Control", chars = "\uE000" },
  # setting as <C-t> to be able to use in nvim
  { key = "Tab", mods = "Control", chars = "\u0014" },
]
