[shell]
program = "/opt/homebrew/bin/fish"

[window]
startup_mode = "Fullscreen"

[colors.primary]
background = "#1f1f28"

[colors]
cursor = { text = "CellBackground", cursor = "#c7c7c7" }

[font]
normal = { family = "Consolas Nerd Font Mono", style = "Regular" }
bold = { family = "Consolas Nerd Font Mono", style = "Bold" }
italic = { family = "Consolas Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Consolas Nerd Font Mono", style = "Bold Italic" }
# size = 15
size = 17

[keyboard]
bindings = [
  # setting as <C-t> to be able to use in nvim
  { key = "Tab", mods = "Control", chars = "\u0014" },
  # setting as <C-u> to be able to use in nvim
  { key = "Enter", mods = "Control", chars = "\u0015" },
]
